# Yandex Swift Style Configuration
disabled_rules:
  - force_cast
  - force_try
  - force_unwrapping
  - identifier_name
  - line_length
  - nesting
  - todo
  - type_name
  - vertical_whitespace

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_nimble
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - reduce_boolean
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - return_value_from_void_function
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - Carthage
  - Pods
  - vendor
  - .build
  - DerivedData
  - Build

analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 250
  error: 500

file_length:
  warning: 400
  error: 600

cyclomatic_complexity:
  warning: 10
  error: 20

function_body_length:
  warning: 50
  error: 100

reporter: "xcode"

